# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-06 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='file',
            field=models.FileField(upload_to='%d %b %Y/%H:%M'),
        ),
    ]
